
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/

mybatis:
  mapper-locations:
  - classpath:mapping/*.xml
  type-aliases-package: com.xyl.model

server:
  port: 9201
  

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dj_xdc_master?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-cloud-provider-center
    
   
    
  
  
  
      



      
      