eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
 #开启熔断器     
feign:
  hystrix:
    enabled: true
    server: 
  port: 9300
  spring: 
  application:
    name: spring-cloud-rest-center
